version: '3.9'

services:
  web:
    image: grgpnmrv/django-project:latest
    build:
      context: ./web
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./web:/app
    expose:
      - 8000
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
